update=1/02/2017 18:57:27
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[eeschema]
version=1
LibDir=../../../../[Resources]/KiCAD Libraries/SparkFun-Kicad-Libraries;../../../../[Resources]/KiCAD Libraries/toolbox.pretty
[eeschema/libraries]
LibName1=NodeMLX-rescue
LibName2=power
LibName3=E:/Dropbox/[Resources]/KiCAD Libraries/SparkFun-Kicad-Libraries/adafruit
LibName4=E:/Dropbox/[Resources]/KiCAD Libraries/SparkFun-Kicad-Libraries/GeekAmmo
LibName5=E:/Dropbox/[Resources]/KiCAD Libraries/SparkFun-Kicad-Libraries/LilyPad-Wearables
LibName6=E:/Dropbox/[Resources]/KiCAD Libraries/SparkFun-Kicad-Libraries/SparkFun-Aesthetics
LibName7=E:/Dropbox/[Resources]/KiCAD Libraries/SparkFun-Kicad-Libraries/SparkFun-AnalogIC
LibName8=E:/Dropbox/[Resources]/KiCAD Libraries/SparkFun-Kicad-Libraries/SparkFun-Boards
LibName9=E:/Dropbox/[Resources]/KiCAD Libraries/SparkFun-Kicad-Libraries/SparkFun-Capacitors
LibName10=E:/Dropbox/[Resources]/KiCAD Libraries/SparkFun-Kicad-Libraries/SparkFun-Connectors
LibName11=E:/Dropbox/[Resources]/KiCAD Libraries/SparkFun-Kicad-Libraries/SparkFun-DigitalIC
LibName12=E:/Dropbox/[Resources]/KiCAD Libraries/SparkFun-Kicad-Libraries/SparkFun-DiscreteSemi
LibName13=E:/Dropbox/[Resources]/KiCAD Libraries/SparkFun-Kicad-Libraries/SparkFun-Displays
LibName14=E:/Dropbox/[Resources]/KiCAD Libraries/SparkFun-Kicad-Libraries/SparkFun-Electromechanical
LibName15=E:/Dropbox/[Resources]/KiCAD Libraries/SparkFun-Kicad-Libraries/SparkFun-FreqCtrl
LibName16=E:/Dropbox/[Resources]/KiCAD Libraries/SparkFun-Kicad-Libraries/SparkFun-LED
LibName17=E:/Dropbox/[Resources]/KiCAD Libraries/SparkFun-Kicad-Libraries/SparkFun-Passives
LibName18=E:/Dropbox/[Resources]/KiCAD Libraries/SparkFun-Kicad-Libraries/SparkFun-PowerIC
LibName19=E:/Dropbox/[Resources]/KiCAD Libraries/SparkFun-Kicad-Libraries/SparkFun-Resistors
LibName20=E:/Dropbox/[Resources]/KiCAD Libraries/SparkFun-Kicad-Libraries/SparkFun-Retired
LibName21=E:/Dropbox/[Resources]/KiCAD Libraries/SparkFun-Kicad-Libraries/SparkFun-RF
LibName22=E:/Dropbox/[Resources]/KiCAD Libraries/SparkFun-Kicad-Libraries/SparkFun-Sensors
LibName23=E:/Dropbox/[Resources]/KiCAD Libraries/SparkFun-Kicad-Libraries/Teensy_3_and_LC_Series_Boards_v1.1
LibName24=E:/Dropbox/[Resources]/KiCAD Libraries/SparkFun-Kicad-Libraries/User-Submitted
LibName25=E:/Dropbox/[Resources]/KiCAD Libraries/toolbox
LibName26=C:/Program Files/KiCad/share/kicad/library/74xgxx
LibName27=C:/Program Files/KiCad/share/kicad/library/74xx
LibName28=C:/Program Files/KiCad/share/kicad/library/ac-dc
LibName29=C:/Program Files/KiCad/share/kicad/library/actel
LibName30=C:/Program Files/KiCad/share/kicad/library/adc-dac
LibName31=C:/Program Files/KiCad/share/kicad/library/allegro
LibName32=C:/Program Files/KiCad/share/kicad/library/Altera
LibName33=C:/Program Files/KiCad/share/kicad/library/analog_devices
LibName34=C:/Program Files/KiCad/share/kicad/library/analog_switches
LibName35=C:/Program Files/KiCad/share/kicad/library/atmel
LibName36=C:/Program Files/KiCad/share/kicad/library/audio
LibName37=C:/Program Files/KiCad/share/kicad/library/battery_management
LibName38=C:/Program Files/KiCad/share/kicad/library/bbd
LibName39=C:/Program Files/KiCad/share/kicad/library/brooktre
LibName40=C:/Program Files/KiCad/share/kicad/library/cmos_ieee
LibName41=C:/Program Files/KiCad/share/kicad/library/cmos4000
LibName42=C:/Program Files/KiCad/share/kicad/library/conn
LibName43=C:/Program Files/KiCad/share/kicad/library/contrib
LibName44=C:/Program Files/KiCad/share/kicad/library/cypress
LibName45=C:/Program Files/KiCad/share/kicad/library/dc-dc
LibName46=C:/Program Files/KiCad/share/kicad/library/device
LibName47=C:/Program Files/KiCad/share/kicad/library/digital-audio
LibName48=C:/Program Files/KiCad/share/kicad/library/diode
LibName49=C:/Program Files/KiCad/share/kicad/library/display
LibName50=C:/Program Files/KiCad/share/kicad/library/dsp
LibName51=C:/Program Files/KiCad/share/kicad/library/elec-unifil
LibName52=C:/Program Files/KiCad/share/kicad/library/ESD_Protection
LibName53=C:/Program Files/KiCad/share/kicad/library/ftdi
LibName54=C:/Program Files/KiCad/share/kicad/library/gennum
LibName55=C:/Program Files/KiCad/share/kicad/library/graphic
LibName56=C:/Program Files/KiCad/share/kicad/library/hc11
LibName57=C:/Program Files/KiCad/share/kicad/library/intel
LibName58=C:/Program Files/KiCad/share/kicad/library/interface
LibName59=C:/Program Files/KiCad/share/kicad/library/ir
LibName60=C:/Program Files/KiCad/share/kicad/library/Lattice
LibName61=C:/Program Files/KiCad/share/kicad/library/linear
LibName62=C:/Program Files/KiCad/share/kicad/library/logo
LibName63=C:/Program Files/KiCad/share/kicad/library/maxim
LibName64=C:/Program Files/KiCad/share/kicad/library/mechanical
LibName65=C:/Program Files/KiCad/share/kicad/library/memory
LibName66=C:/Program Files/KiCad/share/kicad/library/microchip
LibName67=C:/Program Files/KiCad/share/kicad/library/microchip_dspic33dsc
LibName68=C:/Program Files/KiCad/share/kicad/library/microchip_pic10mcu
LibName69=C:/Program Files/KiCad/share/kicad/library/microchip_pic12mcu
LibName70=C:/Program Files/KiCad/share/kicad/library/microchip_pic16mcu
LibName71=C:/Program Files/KiCad/share/kicad/library/microchip_pic18mcu
LibName72=C:/Program Files/KiCad/share/kicad/library/microchip_pic32mcu
LibName73=C:/Program Files/KiCad/share/kicad/library/microcontrollers
LibName74=C:/Program Files/KiCad/share/kicad/library/motor_drivers
LibName75=C:/Program Files/KiCad/share/kicad/library/motorola
LibName76=C:/Program Files/KiCad/share/kicad/library/motors
LibName77=C:/Program Files/KiCad/share/kicad/library/msp430
LibName78=C:/Program Files/KiCad/share/kicad/library/nordicsemi
LibName79=C:/Program Files/KiCad/share/kicad/library/nxp_armmcu
LibName80=C:/Program Files/KiCad/share/kicad/library/onsemi
LibName81=C:/Program Files/KiCad/share/kicad/library/opto
LibName82=C:/Program Files/KiCad/share/kicad/library/Oscillators
LibName83=C:/Program Files/KiCad/share/kicad/library/philips
LibName84=C:/Program Files/KiCad/share/kicad/library/power
LibName85=C:/Program Files/KiCad/share/kicad/library/Power_Management
LibName86=C:/Program Files/KiCad/share/kicad/library/powerint
LibName87=C:/Program Files/KiCad/share/kicad/library/pspice
LibName88=C:/Program Files/KiCad/share/kicad/library/references
LibName89=C:/Program Files/KiCad/share/kicad/library/regul
LibName90=C:/Program Files/KiCad/share/kicad/library/relays
LibName91=C:/Program Files/KiCad/share/kicad/library/rfcom
LibName92=C:/Program Files/KiCad/share/kicad/library/sensors
LibName93=C:/Program Files/KiCad/share/kicad/library/silabs
LibName94=C:/Program Files/KiCad/share/kicad/library/siliconi
LibName95=C:/Program Files/KiCad/share/kicad/library/stm8
LibName96=C:/Program Files/KiCad/share/kicad/library/stm32
LibName97=C:/Program Files/KiCad/share/kicad/library/supertex
LibName98=C:/Program Files/KiCad/share/kicad/library/switches
LibName99=C:/Program Files/KiCad/share/kicad/library/texas
LibName100=C:/Program Files/KiCad/share/kicad/library/transf
LibName101=C:/Program Files/KiCad/share/kicad/library/transistors
LibName102=C:/Program Files/KiCad/share/kicad/library/ttl_ieee
LibName103=C:/Program Files/KiCad/share/kicad/library/valves
LibName104=C:/Program Files/KiCad/share/kicad/library/video
LibName105=C:/Program Files/KiCad/share/kicad/library/wiznet
LibName106=C:/Program Files/KiCad/share/kicad/library/Worldsemi
LibName107=C:/Program Files/KiCad/share/kicad/library/Xicor
LibName108=C:/Program Files/KiCad/share/kicad/library/xilinx
LibName109=C:/Program Files/KiCad/share/kicad/library/zetex
LibName110=C:/Program Files/KiCad/share/kicad/library/Zilog
